import type { ApiEndpoint, ApiService } from '@/types';

// Predefined API endpoints for the API Explorer
export const apiEndpoints: Record<ApiService, ApiEndpoint[]> = {
  control: [
    // Sessions
    { method: 'GET', path: '/sessions', description: 'List all sessions' },
    { method: 'POST', path: '/sessions', description: 'Create new session', body: { symbols: ['AAPL'], start_time: '2025-01-13T09:30:00', end_time: '2025-01-13T16:00:00', initial_capital: 100000 } },
    { method: 'GET', path: '/sessions/{session_id}', description: 'Get session details', params: [{ name: 'session_id', type: 'path', required: true, description: 'Session ID' }] },
    { method: 'DELETE', path: '/sessions/{session_id}', description: 'Delete session', params: [{ name: 'session_id', type: 'path', required: true, description: 'Session ID' }] },
    { method: 'POST', path: '/sessions/{session_id}/start', description: 'Start session', params: [{ name: 'session_id', type: 'path', required: true, description: 'Session ID' }] },
    { method: 'POST', path: '/sessions/{session_id}/pause', description: 'Pause session', params: [{ name: 'session_id', type: 'path', required: true, description: 'Session ID' }] },
    { method: 'POST', path: '/sessions/{session_id}/resume', description: 'Resume session', params: [{ name: 'session_id', type: 'path', required: true, description: 'Session ID' }] },
    { method: 'POST', path: '/sessions/{session_id}/stop', description: 'Stop session', params: [{ name: 'session_id', type: 'path', required: true, description: 'Session ID' }] },
    { method: 'POST', path: '/sessions/{session_id}/speed', description: 'Set replay speed', params: [{ name: 'session_id', type: 'path', required: true, description: 'Session ID' }], body: { speed: 10.0 } },
    { method: 'POST', path: '/sessions/{session_id}/jump', description: 'Jump to timestamp', params: [{ name: 'session_id', type: 'path', required: true, description: 'Session ID' }], body: { timestamp: '2025-01-13T10:00:00' } },
  ],

  alpaca: [
    // Account
    { method: 'GET', path: '/v2/account', description: 'Get account details' },
    // Positions
    { method: 'GET', path: '/v2/positions', description: 'List all positions' },
    { method: 'GET', path: '/v2/positions/{symbol}', description: 'Get position by symbol', params: [{ name: 'symbol', type: 'path', required: true, description: 'Stock symbol', default: 'AAPL' }] },
    { method: 'DELETE', path: '/v2/positions/{symbol}', description: 'Close position', params: [{ name: 'symbol', type: 'path', required: true, description: 'Stock symbol', default: 'AAPL' }] },
    { method: 'DELETE', path: '/v2/positions', description: 'Close all positions' },
    // Orders
    { method: 'GET', path: '/v2/orders', description: 'List orders', params: [{ name: 'status', type: 'query', required: false, description: 'Order status filter', default: 'all' }] },
    { method: 'POST', path: '/v2/orders', description: 'Create order', body: { symbol: 'AAPL', qty: 100, side: 'buy', type: 'market', time_in_force: 'day' } },
    { method: 'GET', path: '/v2/orders/{order_id}', description: 'Get order by ID', params: [{ name: 'order_id', type: 'path', required: true, description: 'Order ID' }] },
    { method: 'DELETE', path: '/v2/orders/{order_id}', description: 'Cancel order', params: [{ name: 'order_id', type: 'path', required: true, description: 'Order ID' }] },
    { method: 'DELETE', path: '/v2/orders', description: 'Cancel all orders' },
    // Market Data
    { method: 'GET', path: '/v2/stocks/{symbol}/trades', description: 'Get trades', params: [{ name: 'symbol', type: 'path', required: true, description: 'Stock symbol', default: 'AAPL' }] },
    { method: 'GET', path: '/v2/stocks/{symbol}/quotes', description: 'Get quotes', params: [{ name: 'symbol', type: 'path', required: true, description: 'Stock symbol', default: 'AAPL' }] },
    { method: 'GET', path: '/v2/stocks/{symbol}/bars', description: 'Get bars', params: [{ name: 'symbol', type: 'path', required: true, description: 'Stock symbol', default: 'AAPL' }] },
    { method: 'GET', path: '/v2/clock', description: 'Get market clock' },
    { method: 'GET', path: '/v2/calendar', description: 'Get trading calendar' },
  ],

  polygon: [
    // Aggregates
    { method: 'GET', path: '/v2/aggs/ticker/{symbol}/range/{multiplier}/{timespan}/{from}/{to}', description: 'Get aggregates/bars', params: [
      { name: 'symbol', type: 'path', required: true, description: 'Stock symbol', default: 'AAPL' },
      { name: 'multiplier', type: 'path', required: true, description: 'Size of timespan (e.g., 1)', default: '1' },
      { name: 'timespan', type: 'path', required: true, description: 'Timespan (minute, hour, day)', default: 'minute' },
      { name: 'from', type: 'path', required: true, description: 'Start date (YYYY-MM-DD)', default: '2025-01-13' },
      { name: 'to', type: 'path', required: true, description: 'End date (YYYY-MM-DD)', default: '2025-01-13' },
    ]},
    { method: 'GET', path: '/v2/aggs/ticker/{symbol}/prev', description: 'Previous day aggregate', params: [{ name: 'symbol', type: 'path', required: true, description: 'Stock symbol', default: 'AAPL' }] },
    // Trades & Quotes
    { method: 'GET', path: '/v3/trades/{symbol}', description: 'Get trades', params: [
      { name: 'symbol', type: 'path', required: true, description: 'Stock symbol', default: 'AAPL' },
      { name: 'timestamp', type: 'query', required: false, description: 'Query by timestamp (YYYY-MM-DD or nanoseconds)' },
      { name: 'timestamp.gte', type: 'query', required: false, description: 'Timestamp greater than or equal to' },
      { name: 'timestamp.lte', type: 'query', required: false, description: 'Timestamp less than or equal to' },
      { name: 'order', type: 'query', required: false, description: 'Order results (asc or desc)', default: 'asc' },
      { name: 'limit', type: 'query', required: false, description: 'Limit results (default 1000, max 50000)', default: '1000' },
      { name: 'sort', type: 'query', required: false, description: 'Sort field', default: 'timestamp' },
    ]},
    { method: 'GET', path: '/v2/last/trade/{symbol}', description: 'Last trade', params: [{ name: 'symbol', type: 'path', required: true, description: 'Stock symbol', default: 'AAPL' }] },
    { method: 'GET', path: '/v3/quotes/{symbol}', description: 'Get quotes', params: [
      { name: 'symbol', type: 'path', required: true, description: 'Stock symbol', default: 'AAPL' },
      { name: 'timestamp', type: 'query', required: false, description: 'Query by timestamp (YYYY-MM-DD or nanoseconds)' },
      { name: 'timestamp.gte', type: 'query', required: false, description: 'Timestamp greater than or equal to' },
      { name: 'timestamp.lte', type: 'query', required: false, description: 'Timestamp less than or equal to' },
      { name: 'order', type: 'query', required: false, description: 'Order results (asc or desc)', default: 'asc' },
      { name: 'limit', type: 'query', required: false, description: 'Limit results (default 1000, max 50000)', default: '1000' },
      { name: 'sort', type: 'query', required: false, description: 'Sort field', default: 'timestamp' },
    ]},
    { method: 'GET', path: '/v2/last/nbbo/{symbol}', description: 'Last NBBO quote', params: [{ name: 'symbol', type: 'path', required: true, description: 'Stock symbol', default: 'AAPL' }] },
    // Snapshots
    { method: 'GET', path: '/v2/snapshot/locale/us/markets/stocks/tickers/{symbol}', description: 'Get ticker snapshot', params: [{ name: 'symbol', type: 'path', required: true, description: 'Stock symbol', default: 'AAPL' }] },
    // Ticker Details
    { method: 'GET', path: '/v3/reference/tickers/{symbol}', description: 'Get ticker details', params: [{ name: 'symbol', type: 'path', required: true, description: 'Stock symbol', default: 'AAPL' }] },
    // Corporate Actions & Reference
    { method: 'GET', path: '/v3/reference/dividends', description: 'Dividends', params: [
      { name: 'ticker', type: 'query', required: false, description: 'Stock symbol', default: 'AAPL' },
      { name: 'limit', type: 'query', required: false, description: 'Limit results', default: '10' },
    ]},
    { method: 'GET', path: '/v3/reference/splits', description: 'Stock splits', params: [
      { name: 'ticker', type: 'query', required: false, description: 'Stock symbol', default: 'AAPL' },
      { name: 'ticker.gte', type: 'query', required: false, description: 'Ticker greater than or equal to' },
      { name: 'ticker.gt', type: 'query', required: false, description: 'Ticker greater than' },
      { name: 'ticker.lte', type: 'query', required: false, description: 'Ticker less than or equal to' },
      { name: 'ticker.lt', type: 'query', required: false, description: 'Ticker less than' },
      { name: 'execution_date', type: 'query', required: false, description: 'Execution date (YYYY-MM-DD)' },
      { name: 'execution_date.gte', type: 'query', required: false, description: 'Execution date greater than or equal to' },
      { name: 'execution_date.gt', type: 'query', required: false, description: 'Execution date greater than' },
      { name: 'execution_date.lte', type: 'query', required: false, description: 'Execution date less than or equal to' },
      { name: 'execution_date.lt', type: 'query', required: false, description: 'Execution date less than' },
      { name: 'sort', type: 'query', required: false, description: 'Sort field (execution_date or ticker)', default: 'execution_date' },
      { name: 'order', type: 'query', required: false, description: 'Order (asc or desc)', default: 'desc' },
      { name: 'limit', type: 'query', required: false, description: 'Limit results', default: '10' },
    ]},
    { method: 'GET', path: '/v2/reference/news', description: 'Ticker news', params: [
      { name: 'ticker', type: 'query', required: false, description: 'Stock symbol', default: 'AAPL' },
      { name: 'published_utc', type: 'query', required: false, description: 'Published timestamp (ISO or YYYY-MM-DD)' },
      { name: 'published_utc.gte', type: 'query', required: false, description: 'Published timestamp greater than or equal to' },
      { name: 'published_utc.gt', type: 'query', required: false, description: 'Published timestamp greater than' },
      { name: 'published_utc.lte', type: 'query', required: false, description: 'Published timestamp less than or equal to' },
      { name: 'published_utc.lt', type: 'query', required: false, description: 'Published timestamp less than' },
      { name: 'order', type: 'query', required: false, description: 'Order (ascending or descending)', default: 'descending' },
      { name: 'sort', type: 'query', required: false, description: 'Sort field (published_utc)', default: 'published_utc' },
      { name: 'include_insights', type: 'query', required: false, description: 'Include insights (true/false)', default: 'true' },
      { name: 'limit', type: 'query', required: false, description: 'Limit results', default: '10' },
    ]},
    { method: 'GET', path: '/vX/reference/ipos', description: 'IPOs', params: [
      { name: 'ticker', type: 'query', required: false, description: 'Stock symbol', default: 'AAPL' },
      { name: 'ipo_status', type: 'query', required: false, description: 'IPO status (e.g. upcoming, history)' },
      { name: 'announced_date', type: 'query', required: false, description: 'Announced date (YYYY-MM-DD)' },
      { name: 'announced_date.gte', type: 'query', required: false, description: 'Announced date greater than or equal to' },
      { name: 'announced_date.gt', type: 'query', required: false, description: 'Announced date greater than' },
      { name: 'announced_date.lte', type: 'query', required: false, description: 'Announced date less than or equal to' },
      { name: 'announced_date.lt', type: 'query', required: false, description: 'Announced date less than' },
      { name: 'listing_date', type: 'query', required: false, description: 'Listing date (YYYY-MM-DD)' },
      { name: 'listing_date.gte', type: 'query', required: false, description: 'Listing date greater than or equal to' },
      { name: 'listing_date.gt', type: 'query', required: false, description: 'Listing date greater than' },
      { name: 'listing_date.lte', type: 'query', required: false, description: 'Listing date less than or equal to' },
      { name: 'listing_date.lt', type: 'query', required: false, description: 'Listing date less than' },
      { name: 'issue_start_date', type: 'query', required: false, description: 'Issue start date (YYYY-MM-DD)' },
      { name: 'issue_start_date.gte', type: 'query', required: false, description: 'Issue start date greater than or equal to' },
      { name: 'issue_start_date.gt', type: 'query', required: false, description: 'Issue start date greater than' },
      { name: 'issue_start_date.lte', type: 'query', required: false, description: 'Issue start date less than or equal to' },
      { name: 'issue_start_date.lt', type: 'query', required: false, description: 'Issue start date less than' },
      { name: 'issue_end_date', type: 'query', required: false, description: 'Issue end date (YYYY-MM-DD)' },
      { name: 'issue_end_date.gte', type: 'query', required: false, description: 'Issue end date greater than or equal to' },
      { name: 'issue_end_date.gt', type: 'query', required: false, description: 'Issue end date greater than' },
      { name: 'issue_end_date.lte', type: 'query', required: false, description: 'Issue end date less than or equal to' },
      { name: 'issue_end_date.lt', type: 'query', required: false, description: 'Issue end date less than' },
      { name: 'last_updated', type: 'query', required: false, description: 'Last updated date (YYYY-MM-DD)' },
      { name: 'last_updated.gte', type: 'query', required: false, description: 'Last updated date greater than or equal to' },
      { name: 'last_updated.gt', type: 'query', required: false, description: 'Last updated date greater than' },
      { name: 'last_updated.lte', type: 'query', required: false, description: 'Last updated date less than or equal to' },
      { name: 'last_updated.lt', type: 'query', required: false, description: 'Last updated date less than' },
      { name: 'sort', type: 'query', required: false, description: 'Sort field', default: 'listing_date' },
      { name: 'order', type: 'query', required: false, description: 'Order (asc or desc)', default: 'desc' },
      { name: 'limit', type: 'query', required: false, description: 'Limit results', default: '10' },
    ]},
    { method: 'GET', path: '/stocks/v1/short-interest', description: 'Short interest', params: [
      { name: 'ticker', type: 'query', required: false, description: 'Stock symbol', default: 'AAPL' },
      { name: 'settlement_date', type: 'query', required: false, description: 'Settlement date (YYYY-MM-DD)' },
      { name: 'settlement_date.gte', type: 'query', required: false, description: 'Settlement date greater than or equal to' },
      { name: 'settlement_date.gt', type: 'query', required: false, description: 'Settlement date greater than' },
      { name: 'settlement_date.lte', type: 'query', required: false, description: 'Settlement date less than or equal to' },
      { name: 'settlement_date.lt', type: 'query', required: false, description: 'Settlement date less than' },
      { name: 'sort', type: 'query', required: false, description: 'Sort field (settlement_date or ticker)', default: 'settlement_date' },
      { name: 'order', type: 'query', required: false, description: 'Order (asc or desc)', default: 'desc' },
      { name: 'limit', type: 'query', required: false, description: 'Limit results', default: '10' },
    ]},
    { method: 'GET', path: '/stocks/v1/short-volume', description: 'Short volume', params: [
      { name: 'ticker', type: 'query', required: false, description: 'Stock symbol', default: 'AAPL' },
      { name: 'date', type: 'query', required: false, description: 'Trade date (YYYY-MM-DD)' },
      { name: 'date.gte', type: 'query', required: false, description: 'Trade date greater than or equal to' },
      { name: 'date.gt', type: 'query', required: false, description: 'Trade date greater than' },
      { name: 'date.lte', type: 'query', required: false, description: 'Trade date less than or equal to' },
      { name: 'date.lt', type: 'query', required: false, description: 'Trade date less than' },
      { name: 'sort', type: 'query', required: false, description: 'Sort field (date or ticker)', default: 'date' },
      { name: 'order', type: 'query', required: false, description: 'Order (asc or desc)', default: 'desc' },
      { name: 'limit', type: 'query', required: false, description: 'Limit results', default: '10' },
    ]},
    { method: 'GET', path: '/vX/reference/tickers/{id}/events', description: 'Ticker events', params: [
      { name: 'id', type: 'path', required: true, description: 'Ticker/CUSIP/FIGI', default: 'AAPL' },
      { name: 'limit', type: 'query', required: false, description: 'Limit results', default: '10' },
    ]},
    { method: 'GET', path: '/vX/reference/financials', description: 'Financials', params: [
      { name: 'ticker', type: 'query', required: false, description: 'Stock symbol', default: 'AAPL' },
      { name: 'timeframe', type: 'query', required: false, description: 'Timeframe (annual or quarterly)', default: 'annual' },
      { name: 'cik', type: 'query', required: false, description: 'CIK identifier' },
      { name: 'fiscal_period', type: 'query', required: false, description: 'Fiscal period (e.g. Q1, Q2, FY, TTM)' },
      { name: 'fiscal_year', type: 'query', required: false, description: 'Fiscal year (YYYY)' },
      { name: 'period_of_report_date', type: 'query', required: false, description: 'Period of report date (YYYY-MM-DD)' },
      { name: 'period_of_report_date.gte', type: 'query', required: false, description: 'Period of report date greater than or equal to' },
      { name: 'period_of_report_date.gt', type: 'query', required: false, description: 'Period of report date greater than' },
      { name: 'period_of_report_date.lte', type: 'query', required: false, description: 'Period of report date less than or equal to' },
      { name: 'period_of_report_date.lt', type: 'query', required: false, description: 'Period of report date less than' },
      { name: 'filing_date', type: 'query', required: false, description: 'Filing date (YYYY-MM-DD)' },
      { name: 'filing_date.gte', type: 'query', required: false, description: 'Filing date greater than or equal to' },
      { name: 'filing_date.gt', type: 'query', required: false, description: 'Filing date greater than' },
      { name: 'filing_date.lte', type: 'query', required: false, description: 'Filing date less than or equal to' },
      { name: 'filing_date.lt', type: 'query', required: false, description: 'Filing date less than' },
      { name: 'sort', type: 'query', required: false, description: 'Sort field (period_of_report_date or filing_date)', default: 'period_of_report_date' },
      { name: 'order', type: 'query', required: false, description: 'Order (asc or desc)', default: 'desc' },
      { name: 'limit', type: 'query', required: false, description: 'Limit results', default: '10' },
    ]},
    // Market Status
    { method: 'GET', path: '/v1/marketstatus/now', description: 'Current market status' },
  ],

  finnhub: [
    // Real-time
    { method: 'GET', path: '/quote', description: 'Get quote', params: [{ name: 'symbol', type: 'query', required: true, description: 'Stock symbol', default: 'AAPL' }] },
    // Historical
    { method: 'GET', path: '/stock/candle', description: 'Get candles/OHLCV', params: [
      { name: 'symbol', type: 'query', required: true, description: 'Stock symbol', default: 'AAPL' },
      { name: 'resolution', type: 'query', required: true, description: 'Resolution (1, 5, 15, 30, 60, D, W, M)', default: '1' },
      { name: 'from', type: 'query', required: true, description: 'Start timestamp (Unix)', default: '1736768400' },
      { name: 'to', type: 'query', required: true, description: 'End timestamp (Unix)', default: '1736791800' },
    ]},
    // Company Info
    { method: 'GET', path: '/stock/profile2', description: 'Company profile', params: [{ name: 'symbol', type: 'query', required: true, description: 'Stock symbol', default: 'AAPL' }] },
    { method: 'GET', path: '/stock/peers', description: 'Company peers', params: [{ name: 'symbol', type: 'query', required: true, description: 'Stock symbol', default: 'AAPL' }] },
    // News
    { method: 'GET', path: '/company-news', description: 'Company news', params: [
      { name: 'symbol', type: 'query', required: true, description: 'Stock symbol', default: 'AAPL' },
      { name: 'from', type: 'query', required: false, description: 'From date (YYYY-MM-DD)' },
      { name: 'to', type: 'query', required: false, description: 'To date (YYYY-MM-DD)' },
    ]},
    { method: 'GET', path: '/news', description: 'Market news', params: [{ name: 'category', type: 'query', required: false, description: 'News category', default: 'general' }] },
    // Corporate Actions
    { method: 'GET', path: '/stock/dividend', description: 'Dividends', params: [{ name: 'symbol', type: 'query', required: true, description: 'Stock symbol', default: 'AAPL' }] },
    { method: 'GET', path: '/stock/split', description: 'Stock splits', params: [{ name: 'symbol', type: 'query', required: true, description: 'Stock symbol', default: 'AAPL' }] },
    // Analyst
    { method: 'GET', path: '/stock/recommendation', description: 'Analyst recommendations', params: [{ name: 'symbol', type: 'query', required: true, description: 'Stock symbol', default: 'AAPL' }] },
    { method: 'GET', path: '/stock/price-target', description: 'Price targets', params: [{ name: 'symbol', type: 'query', required: true, description: 'Stock symbol', default: 'AAPL' }] },
  ],
};
